<?php

namespace ContainerPFZcKNs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPublicListingControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Infrastructure\Api\Controller\PublicListingController' shared autowired service.
     *
     * @return \App\Infrastructure\Api\Controller\PublicListingController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Infrastructure/Api/Controller/PublicListingController.php';

        return $container->services['App\\Infrastructure\\Api\\Controller\\PublicListingController'] = new \App\Infrastructure\Api\Controller\PublicListingController();
    }
}
