<?php

namespace ContainerCRVwxVy;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Fq3YQYZService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.fq3YQYZ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.fq3YQYZ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'useCase' => ['privates', 'App\\Application\\UseCase\\CalculateScoreUseCase', 'getCalculateScoreUseCaseService', true],
        ], [
            'useCase' => 'App\\Application\\UseCase\\CalculateScoreUseCase',
        ]);
    }
}
