<?php

namespace ContainerCRVwxVy;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCalculateScoreUseCaseService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Application\UseCase\CalculateScoreUseCase' shared autowired service.
     *
     * @return \App\Application\UseCase\CalculateScoreUseCase
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Application/UseCase/CalculateScoreUseCase.php';
        include_once \dirname(__DIR__, 4).'/src/Application/Service/DataRetrievalService.php';
        include_once \dirname(__DIR__, 4).'/src/Domain/Interface/AdPersistenceInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Infrastructure/Persistence/InFileSystemAdPersistence.php';
        include_once \dirname(__DIR__, 4).'/src/Domain/Interface/PicturePersistenceInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Infrastructure/Persistence/InFileSystemPicturePersistance.php';
        include_once \dirname(__DIR__, 4).'/src/Domain/Service/CalculateScore.php';

        $a = new \App\Infrastructure\Persistence\InFileSystemPicturePersistence();

        return $container->privates['App\\Application\\UseCase\\CalculateScoreUseCase'] = new \App\Application\UseCase\CalculateScoreUseCase(new \App\Application\Service\DataRetrievalService(new \App\Infrastructure\Persistence\InFileSystemAdPersistence(), $a), new \App\Domain\Service\CalculateScore($a));
    }
}
