<?php

namespace ContainerCRVwxVy;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCalculateScoreControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Infrastructure\Api\Controller\CalculateScoreController' shared autowired service.
     *
     * @return \App\Infrastructure\Api\Controller\CalculateScoreController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Infrastructure/Api/Controller/CalculateScoreController.php';

        $container->services['App\\Infrastructure\\Api\\Controller\\CalculateScoreController'] = $instance = new \App\Infrastructure\Api\Controller\CalculateScoreController(($container->privates['App\\Application\\UseCase\\CalculateScoreUseCase'] ?? $container->load('getCalculateScoreUseCaseService')));

        $instance->setContainer((new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'http_kernel' => ['services', 'http_kernel', 'getHttpKernelService', false],
            'parameter_bag' => ['privates', 'parameter_bag', 'getParameterBagService', false],
            'request_stack' => ['services', 'request_stack', 'getRequestStackService', false],
            'router' => ['services', 'router', 'getRouterService', false],
            'session' => ['services', 'session', 'getSessionService', true],
        ], [
            'http_kernel' => '?',
            'parameter_bag' => '?',
            'request_stack' => '?',
            'router' => '?',
            'session' => '?',
        ]))->withContext('App\\Infrastructure\\Api\\Controller\\CalculateScoreController', $container));

        return $instance;
    }
}
