<?php

namespace ContainerCRVwxVy;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getQualityListingControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Infrastructure\Api\Controller\QualityListingController' shared autowired service.
     *
     * @return \App\Infrastructure\Api\Controller\QualityListingController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Infrastructure/Api/Controller/QualityListingController.php';

        return $container->services['App\\Infrastructure\\Api\\Controller\\QualityListingController'] = new \App\Infrastructure\Api\Controller\QualityListingController();
    }
}
