calculate_score:
    path: /ads/calculate-score
    controller: 'App\Infrastructure\Api\Controller\CalculateScoreController::__invoke'
    methods: GET

public_listing:
    path: /ads/public-listing
    controller: 'App\Infrastructure\Api\Controller\PublicListingController::__invoke'
    methods: GET

quality_listing:
    path: /ads/quality-listing
    controller: 'App\Infrastructure\Api\Controller\QualityListingController::__invoke'
    methods: GET

