<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerP9xgi0c\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerP9xgi0c/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerP9xgi0c.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerP9xgi0c\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerP9xgi0c\App_KernelDevDebugContainer([
    'container.build_hash' => 'P9xgi0c',
    'container.build_id' => 'd5d287d2',
    'container.build_time' => 1708116121,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerP9xgi0c');
