<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEuglOfi\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEuglOfi/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEuglOfi.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEuglOfi\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerEuglOfi\App_KernelDevDebugContainer([
    'container.build_hash' => 'EuglOfi',
    'container.build_id' => '4c274017',
    'container.build_time' => 1708109821,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEuglOfi');
