<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCRVwxVy\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCRVwxVy/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCRVwxVy.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCRVwxVy\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerCRVwxVy\App_KernelDevDebugContainer([
    'container.build_hash' => 'CRVwxVy',
    'container.build_id' => 'c3b9b00b',
    'container.build_time' => 1708106403,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCRVwxVy');
